

services:
  server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    image: scplant_backend_server
    container_name: "scplant_backend_server"
    command: sh -c ". ~/.bashrc && python3 manage.py runserver 0.0.0.0:8000"
    tty: true
    restart: always
    ports:
      - '8449:8000'
    expose:
      - 8449
    volumes:
      - .:/home/scplant_backend/
    working_dir: /home/scplant_backend/core/
    env_file:
      - server.env
    networks:
      - default

